_posts/2015-11-14-lifetime-part1.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/30)

Исправлена пара опечаток

---

_layouts/post.html
index.html

Исправление #29
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/31)

Кнопка комментариев плохо работает - #29

---

index.html

Забыл, что в data-disqus-url нужно весь url указывать. Можно использовать data-disqus-identifier, но я пока что не представляю что он из себя представляет
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/32)

fix disqus counter

---

_posts/2015-11-14-lifetime-part2.md

Во второй статье про время жизни была небольшая путаница с названием структуры, поправил
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/39)

Исправил Person на Customer

---

_posts/2015-11-14-lifetime-part2.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/42)

пропущенное mut объявление Customer`а

---

_posts/2015-12-04-ide-for-rust.md

Fix #46, #47
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/48)

Возможное исправление статьи про IDE

---

_posts/2015-12-04-ide-for-rust.md

Испарвление ide-for-rust.md

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/50)

Локальный запуск

---

_posts/2015-11-14-lifetime-part1.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/61)

Исправление опечаток

---

_sass/style.scss
index.html

Чтобы самому "поиграться" с цветом, не собирая сайт у себя, нужно:
1) Открыть просмотр кода кнопки (обычно есть пункт в контекстном меню)
2) Для блока 
```
<a href="/archive.html" class="btn btn-default all-posts">все публикации</a>
```
выбрать в контекстном меню "отредактировать как HTML", и добавить класс `btn-primary`:
```
<a href="/archive.html" class="btn btn-default all-posts btn-primary">все публикации</a>
```
3) Перейти на вкладку `Sources`, открыть файл `main.css` и в любое его место добавить
```
.btn-primary {
background-color: #A86A2D;
border-color: #99652E; }
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/60)

Стиль для кнопки "все публикации"

---

.travis.yml
_includes/head.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/63)

Используем dns-prefetch для ускорения загрузки

---

_sass/style.scss
index.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/67)

Добавляем кнопку "все записи" сверху

---

_includes/footer.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/71)

fix year in footer

---

_posts/2016-01-28-rustycrate-plans-2016.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/73)

испправил опечатку в описании kernlog

---

_sass/style.scss

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/81)

Убрать чат на маленьких экранах

---

_includes/header.html

Выглядит вот так:
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/82)

Делаем более понятную навигацию

---

_layouts/post.html

Fix #72
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/84)

Чиним конфигурацию Disqus

---

.travis.yml

Игнорируем верификационные файлы
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/86)

Снова включаем htmlproofer

---

_config.yml
archive.html
feed.xml
index.html
sitemap.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/88)

Реализуем карту сайта без плагинов

---

adopters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/97)

Добавил ссылку на Twitter

---

_includes/header.html
adopters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/98)

Замена страницы "Rust в продакшен" на "Кто использует Rust" добавлены ссылки и описание.

---

_includes/header.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/113)

Added link to ruRust/gamedev to dropdown menu

---

_posts/2016-07-11-rust-1.10.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/116)

Анонс 1.10

---

_includes/header.html

Добавил ссылку на Rust на примерах. Это перевод rustbyexample.com. В данный момент находится в процессе перевода.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/124)

Добавил ссылку на Rust на примерах

---

_posts/2016-09-29-rust-1.12.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/139)

ipv4addr typo

---

_includes/header.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/140)

Исправление ссылки на Rust на примерах

---

_includes/head.html

Добавил метатеги для Twitter'а. Теперь при публикации url'а статьи, твиттером должны подтягиваться некоторые данные о ней. Как я понял, у постов нет описания и главной картинки, так что такие теги как twitter:image и twitter:description не добавлял.
Close #153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/154)

Добавил метатеги для Twitter'а

---

community-projects.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/159)

Add ZoC to community-projects.md

---

dictionary.md

безусловный шаблон
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/166)

Irrefutable pattern

---

contacts.html

Исправил фамилию :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/179)

Ошибка в фамилии

---

_includes/post-header-text.html

Предлагаю немного изменить шапку постов
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/180)

Улучшить шапку постов

---

_includes/category-index.html
howtos.html
news.html
thoughts.html
tutorials.html

#145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/189)

Меняем отображение категорий

---

patrons.md

Частично исправляет #188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/190)

Исправляем проблему с торчащими ссылками

---

_includes/footer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/192)

Пробуем ускорить загрузку страниц

---

rules.md

https://gitter.im/ruRust/rustycrate.ru?at=58da5b3c4cb8d09173352302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/206)

Правила: убрал про совет про ржавый CoC

---

community-projects.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/232)

Added Zemeroth project to community-projects.md

---

_posts/2018-01-29-tokio-asyncio.md

Плюс поправил ссылку на оригинал
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/264)

2018-01-29-tokio-asyncio.md: Исправил заголовок на переведенный

---

_posts/2018-02-03-not-explicit.md

https://gitter.im/ruRust/rustycrate.ru?at=5a781d807dcd63481f1bf559
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/269)

Удалил залетный BOM, ломающий Jekyll

---

.travis.yml

Fix #270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/286)

Добавляем на CI проверку BOMов

---

.travis.yml
_assets/css/style.scss
_includes/header.html

Fix #173 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/287)

Добавляем кнопку "вверх"

---

_posts/2017-05-02-rust-1.17.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/291)

Исправляем сломанную ссылку

---

_includes/header.html
books.md

с https://rustbook.kinoher.ml/ на http://rustbook.github.io/
Fix #310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/314)

Исправляем ссылку на The Rust Programming Language

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/321)

Перенос сайта

---

_includes/comments.html
rules.md

#318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rustycrate.ru/322)

Удаление rustycrate's reddit
